#!/usr/bin/env python

from __future__ import print_function

import os
import json
import sys
import subprocess
import traceback

# These are the paths to where SageMaker mounts interesting things in your container.
prefix = '/opt/ml/'
param_path = os.path.join(prefix, 'input/config/hyperparameters.json')
training_script = '/opt/ml/detectron2/tools/plain_train_net.py'


if __name__ == '__main__':
    with open(param_path, 'r') as tc:
        hyperparams = json.load(tc)
        
    python_executable = sys.executable
    num_gpus = hyperparams['num_gpus']
    config = hyperparams['config_file']

    train_cmd = f"{python_executable} {training_script} --config_file {config} --num_gpus {num_gpus}"
    #+ sage_params['sagemaker_submit_directory']
    print('train_cmd: ',train_cmd)

    os.system(train_cmd) # " ".join(train_cmd)